export enum AnalysisType {
    PERFORMANCE = "PERFORMANCE",
    COMPARISON = "COMPARISON",
    DIAGNOSIS = "DIAGNOSIS",
    TREND = "TREND",
    OPPORTUNITY = "OPPORTUNITY",
    RISK = "RISK",
    FORECAST = "FORECAST",
}